### ISSUE TITLE
生产新文件的摘要文件为什么这么大

### ISSUE THREAD

**Issue by rewerma** [9468305/crsync#2]
生产新文件的摘要文件为什么这么大，看了内容好像就只是在源文件前面加了了tpl信息

**Comment by 9468305** [comment]
具体数字是？摘要文件肯定很小才对。

**Comment by rewerma** [comment]
我直接运行：
```
crsync.exe digest C:\Dev\test.txt C:\Dev\test2 4
```
其中test.txt里面只有几个字符串大小只有318字节
生成的test2却有378字节

**Comment by rewerma** [comment]
看源码明白了，是文件太小了，全部是restdata了
