### ISSUE TITLE
征集需求

### ISSUE THREAD

**Issue by 9468305** [9468305/crsync#3]
这个库自2016之后就没有更新了。主要是因为已经跳槽，新工作业务场景上没有需求。
如果有人需要这个方案，可以提出，看看有无必要继续优化一下。
目前还是很不完善的状态。

**Comment by rewerma** [comment]
希望能增加本地文件到本地文件增量同步的功能

**Comment by 9468305** [comment]
1. Desktop 本地到本地（以及局域网内部主机之间）的文件增量同步，是rsync默认功能。可以直接使用Linux rsync命令：`rsync [OPTION]... SRC DEST` 。
2. 服务器主机之间文件增量备份，Google DevOps有一个封装好的相关脚本，好像叫gsutil rsync。https://github.com/GoogleCloudPlatform/gsutil/blob/master/gslib/commands/rsync.py
3. [Rclone - rsync for cloud storage](https://rclone.org/)
