### ISSUE TITLE
具体更新方式

### ISSUE THREAD

**Issue by stamaimer** [9468305/crsync#4]
麻烦问下对于版本更新，是针对两个版本间发生变化的文件分别进行摘要计算，对比，更新，
还是整包生成摘要，客户端本地存在上个版本的整包，然后进行整包对比更新？

**Comment by 9468305** [comment]
我写了一个workflow mermaid流程图，但是GitHub markdown不支持mermaid在线展示。请看[这里](https://mermaid-js.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBzdWJncmFwaCBTZXJ2ZXItU2lkZVxuICAgIFJlbW90ZVtQQy9TZXJ2ZXIvSG9zdF0gLS0-fEdlbmVyYXRlfEZpbGUyW0FwcC9OZXcgRmlsZSAyLjBdXG4gICAgRmlsZTIgLS0-fGNyc3luYyBkaWdlc3R8IERpZ2VzdDIoQXBwL05ldyBEaWdlc3QgMi4wKVxuICAgIGVuZFxuXG4gICAgc3ViZ3JhcGggQ0ROLVNpZGVcbiAgICBGaWxlMkNETltBcHAvTmV3IEZpbGUgMi4wXVxuICAgIERpZ2VzdDJDRE5bQXBwL05ldyBEaWdlc3QgMi4wXVxuICAgIGVuZFxuXG4gICAgc3ViZ3JhcGggQ2xpZW50LVNpZGVcbiAgICBGaWxlMVtQQy9DbGllbnQvTW9iaWxlIEFwcC9PbGQgRmlsZSAxLjBdXG5cbiAgICAgICAgc3ViZ3JhcGggQ3JzeW5jLUludGVybmFsXG4gICAgICAgIENyc3luY01hdGNoe2Nyc3luYyBtYXRjaH0gLS0-fENhbGN1bGF0ZXxQYXRjaEluZGV4XG4gICAgICAgIFBhdGNoSW5kZXggLS0-Q3JzeW5jUGF0Y2h7Y3JzeW5jIHBhdGNofVxuICAgICAgICBlbmRcblxuICAgIENyc3luY1BhdGNoIC0tPnxtZW1jcHl8RmlsZTJMb2NhbFtBcHAvTmV3IEZpbGUgMi4wXVxuICAgIGVuZFxuXG5GaWxlMiAtLT58RGVwbG95fEZpbGUyQ0ROXG5EaWdlc3QyIC0tPnxEZXBsb3l8RGlnZXN0MkNETlxuRmlsZTEgLS0-IHxGdWxsIEZpbGUgQ29udGVudHxDcnN5bmNNYXRjaFxuRGlnZXN0MkNETiAtLT58Y3VybCBkb3dubG9hZHxDcnN5bmNNYXRjaFxuRmlsZTJDRE4gLS0-fGN1cmwgaHR0cCBjaHVua3xDcnN5bmNQYXRjaFxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImZvcmVzdCIsInRoZW1lVmFyaWFibGVzIjp7ImJhY2tncm91bmQiOiJ3aGl0ZSIsInByaW1hcnlDb2xvciI6IiNjZGU0OTgiLCJzZWNvbmRhcnlDb2xvciI6IiNjZGZmYjIiLCJtYWluQmtnIjoiI2NkZTQ5OCIsInNlY29uZEJrZyI6IiNjZGZmYjIiLCJsaW5lQ29sb3IiOiIjMDAwMDAwIiwiYm9yZGVyMSI6IiMxMzU0MGMiLCJib3JkZXIyIjoiIzZlYWE0OSIsImFycm93aGVhZENvbG9yIjoiZ3JlZW4iLCJmb250RmFtaWx5IjoiXCJ0cmVidWNoZXQgbXNcIiwgdmVyZGFuYSwgYXJpYWwiLCJmb250U2l6ZSI6IjE2cHgiLCJ0ZXJ0aWFyeUNvbG9yIjoiaHNsKDc4LjE1Nzg5NDczNjgsIDU4LjQ2MTUzODQ2MTUlLCA4NC41MDk4MDM5MjE2JSkiLCJwcmltYXJ5Qm9yZGVyQ29sb3IiOiJoc2woNzguMTU3ODk0NzM2OCwgMTguNDYxNTM4NDYxNSUsIDY0LjUwOTgwMzkyMTYlKSIsInNlY29uZGFyeUJvcmRlckNvbG9yIjoiaHNsKDk4Ljk2MTAzODk2MSwgNjAlLCA3NC45MDE5NjA3ODQzJSkiLCJ0ZXJ0aWFyeUJvcmRlckNvbG9yIjoiaHNsKDc4LjE1Nzg5NDczNjgsIDE4LjQ2MTUzODQ2MTUlLCA3NC41MDk4MDM5MjE2JSkiLCJwcmltYXJ5VGV4dENvbG9yIjoiIzMyMWI2NyIsInNlY29uZGFyeVRleHRDb2xvciI6IiMzMjAwNGQiLCJ0ZXJ0aWFyeVRleHRDb2xvciI6IiMzMjFiNjciLCJ0ZXh0Q29sb3IiOiIjMDAwMDAwIiwibm9kZUJrZyI6IiNjZGU0OTgiLCJub2RlQm9yZGVyIjoiIzEzNTQwYyIsImNsdXN0ZXJCa2ciOiIjY2RmZmIyIiwiY2x1c3RlckJvcmRlciI6IiM2ZWFhNDkiLCJkZWZhdWx0TGlua0NvbG9yIjoiIzAwMDAwMCIsInRpdGxlQ29sb3IiOiIjMzMzIiwiZWRnZUxhYmVsQmFja2dyb3VuZCI6IiNlOGU4ZTgiLCJhY3RvckJvcmRlciI6ImhzbCg3OC4xNTc4OTQ3MzY4LCA1OC40NjE1Mzg0NjE1JSwgNTQuNTA5ODAzOTIxNiUpIiwiYWN0b3JCa2ciOiIjY2RlNDk4IiwiYWN0b3JUZXh0Q29sb3IiOiJibGFjayIsImFjdG9yTGluZUNvbG9yIjoiZ3JleSIsInNpZ25hbENvbG9yIjoiIzMzMyIsInNpZ25hbFRleHRDb2xvciI6IiMzMzMiLCJsYWJlbEJveEJrZ0NvbG9yIjoiI2NkZTQ5OCIsImxhYmVsQm94Qm9yZGVyQ29sb3IiOiIjMzI2OTMyIiwibGFiZWxUZXh0Q29sb3IiOiJibGFjayIsImxvb3BUZXh0Q29sb3IiOiJibGFjayIsIm5vdGVCb3JkZXJDb2xvciI6IiM2ZWFhNDkiLCJub3RlQmtnQ29sb3IiOiIjZmZmNWFkIiwibm90ZVRleHRDb2xvciI6ImJsYWNrIiwiYWN0aXZhdGlvbkJvcmRlckNvbG9yIjoiIzY2NiIsImFjdGl2YXRpb25Ca2dDb2xvciI6IiNmNGY0ZjQiLCJzZXF1ZW5jZU51bWJlckNvbG9yIjoid2hpdGUiLCJzZWN0aW9uQmtnQ29sb3IiOiIjNmVhYTQ5IiwiYWx0U2VjdGlvbkJrZ0NvbG9yIjoid2hpdGUiLCJzZWN0aW9uQmtnQ29sb3IyIjoiIzZlYWE0OSIsInRhc2tCb3JkZXJDb2xvciI6IiMxMzU0MGMiLCJ0YXNrQmtnQ29sb3IiOiIjNDg3ZTNhIiwidGFza1RleHRMaWdodENvbG9yIjoid2hpdGUiLCJ0YXNrVGV4dENvbG9yIjoid2hpdGUiLCJ0YXNrVGV4dERhcmtDb2xvciI6ImJsYWNrIiwidGFza1RleHRPdXRzaWRlQ29sb3IiOiJibGFjayIsInRhc2tUZXh0Q2xpY2thYmxlQ29sb3IiOiIjMDAzMTYzIiwiYWN0aXZlVGFza0JvcmRlckNvbG9yIjoiIzEzNTQwYyIsImFjdGl2ZVRhc2tCa2dDb2xvciI6IiNjZGU0OTgiLCJncmlkQ29sb3IiOiJsaWdodGdyZXkiLCJkb25lVGFza0JrZ0NvbG9yIjoibGlnaHRncmV5IiwiZG9uZVRhc2tCb3JkZXJDb2xvciI6ImdyZXkiLCJjcml0Qm9yZGVyQ29sb3IiOiIjZmY4ODg4IiwiY3JpdEJrZ0NvbG9yIjoicmVkIiwidG9kYXlMaW5lQ29sb3IiOiJyZWQiLCJsYWJlbENvbG9yIjoiYmxhY2siLCJlcnJvckJrZ0NvbG9yIjoiIzU1MjIyMiIsImVycm9yVGV4dENvbG9yIjoiIzU1MjIyMiIsImNsYXNzVGV4dCI6IiMzMjFiNjciLCJmaWxsVHlwZTAiOiIjY2RlNDk4IiwiZmlsbFR5cGUxIjoiI2NkZmZiMiIsImZpbGxUeXBlMiI6ImhzbCgxNDIuMTU3ODk0NzM2OCwgNTguNDYxNTM4NDYxNSUsIDc0LjUwOTgwMzkyMTYlKSIsImZpbGxUeXBlMyI6ImhzbCgxNjIuOTYxMDM4OTYxLCAxMDAlLCA4NC45MDE5NjA3ODQzJSkiLCJmaWxsVHlwZTQiOiJoc2woMTQuMTU3ODk0NzM2OCwgNTguNDYxNTM4NDYxNSUsIDc0LjUwOTgwMzkyMTYlKSIsImZpbGxUeXBlNSI6ImhzbCgzNC45NjEwMzg5NjEsIDEwMCUsIDg0LjkwMTk2MDc4NDMlKSIsImZpbGxUeXBlNiI6ImhzbCgyMDYuMTU3ODk0NzM2OCwgNTguNDYxNTM4NDYxNSUsIDc0LjUwOTgwMzkyMTYlKSIsImZpbGxUeXBlNyI6ImhzbCgyMjYuOTYxMDM4OTYxLCAxMDAlLCA4NC45MDE5NjA3ODQzJSkifX0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)

如果这个流程图仍然不够清晰，欢迎继续讨论。  

BTW：  
我看您的个人资料是腾讯深圳员工？IEG吗？是否手游项目需要类似增量更新方案？  
我离开IEG之后，由于现在工作无合适业务场景，所以很久没有更新该方案了。  
如果有需要，我们可以合作一把。

**Comment by 9468305** [comment]
直接回答你提出的问题：  
客户端本地文件 + 下载服务端最新文件的摘要文件（size 很小），本地计算出差异部分（文件中差异数据的起始位置和偏移量）。 
 
然后curl http chunk 下载服务端最新文件的差异区块部分。  
最后直接合成写入本地新文件。这样就完成了。
